name: CI

permissions: {}

on:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  solidity:
    name: Solidity (Foundry)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check
        env:
          FOUNDRY_PROFILE: ci

      - name: Run Forge lint
        run: forge lint
        env:
          FOUNDRY_PROFILE: ci

      - name: Run Forge gas snapshot test
        run: forge snapshot --match-path "test/gas/*.t.sol" --check --tolerance 3
        env:
          FOUNDRY_PROFILE: ci

      - name: Run Forge build
        run: forge build --sizes
        env:
          FOUNDRY_PROFILE: ci

      - name: Run Forge tests
        run: forge test
        env:
          FOUNDRY_PROFILE: ci
